export interface Users {    
    id:string,
    name:string,
    username:string
    email:string,
    address:{
        city:string
    }
    ride:string,
    days:string,
    posts:[{
        userId:string,
        id:string,
        title:string,
        body:string
    }],
    albums:[{
        userId:string,
        id:string,
        title:string,
        photos:[{
            albumId:string,
            id:string,
            title:string,
            url:string,
            thumbnailUrl:string
        }]
    }]   
   }